#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("GUI.Resource", IsApplication=true)]

namespace GUI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050002
			public const int bigHorMargin = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int medHorMargin = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int smaHorMargin = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Chart1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int logoCel = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int logoSm = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int monoandroidsplash = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int button1 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int button2 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int button3 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int button4 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int button5 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int button6 = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int imageView1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int myButton = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int plotview = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int radioButton1 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int radioButton2 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int radioButton3 = 2131165196;
			
			// aapt resource value: 0x7f070009
			public const int radioGroup1 = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Invent = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LostSales = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PlotActivity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Rotation = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Sales = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Service = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040008
			public const int app_name = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int grlRep = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int invent = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int lostSales = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int rotation = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int service = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int stoRep = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int supply = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int warnings = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
